### ISSUE TITLE
Cannot see history older than one day , cannot browse history with scroll

### ISSUE THREAD

**Issue by razor74** [ppawel/openstreetmap-website#27]
Hi. from yesterday i notticed that i cannot browse the history in the left panel - older than one day and no icons for user modiffications apear. Before of this i can browse history over a place even one year in the past or more. There is curently a problem with owl api?

**Comment by ppawel** [comment]
Oops, you are right - it looks like I broke it :-) Will fix soon.

**Comment by ppawel** [comment]
Should be fixed now.

**Comment by razor74** [comment]
Still not working :(

The left history panel show only one page and cannot browse for more history. You can see the missing part of bottom panel cursor for browsing. The cursor is down to the limit and the arrow is missing like the panel didn\t show completely.
The history i can see is one day, no more...

**Comment by razor74** [comment]
i cannot attach an image...

**Comment by ppawel** [comment]
OK, I will check this again.

**Comment by ppawel** [comment]
Problem with missing down arrow reported to the main repository:

openstreetmap/openstreetmap-website/issues/500

**Comment by ppawel** [comment]
What web browser do you use? I can't reproduce this problem anymore on Chromium and Firefox on Linux.

**Comment by razor74** [comment]
Firefox most of the time and Chrome from time to time. on both was the 
problem. And windows 64 bit.
Now the history panel works like before. I can roll down again and again 
with mouse scroll and i can see the history older than one day.
The down arrow of the history panel still missing... But for me is 
enough that i can see all the history older than one day.

Thanks

**Comment by ppawel** [comment]
OK, thanks for the info. Closing for now, let me know when you have any problems with this again.

**Comment by razor74** [comment]
Hello again.
The history didn't work from  8 days ago. You know what's hapening?

**Comment by ppawel** [comment]
It is processing again.

**Comment by ppawel** [comment]
Please keep in mind that the site is most certainly NOT in production state - it is still a very early beta. More importantly, the version that is currently running has some major bugs and I am aware of the fact that it is losing history etc. This is fixed already in the new version which I am preparing to roll out but I need a little bit more time.

This new version should be the one that maybe some day goes into production (osm.org website integration). For now it's still just a preview / experiment.

Thank you for your interest though, it really helps with motivation to know that people care about this stuff.
